### ISSUE TITLE
I use resizeBilinear function,but now it seems to guess everything as the great wall of china.

### ISSUE THREAD

**Issue by Qingyoum** [larswaechter/quickdraw-cnn#2]
```
  const tensor = tf.tidy(
    () =>
      tf.image
        .resizeBilinear(
          tf.browser.fromPixels(document.querySelector("#defaultCanvas0")),
          [28, 28],
          true
        )
        .slice([0, 0, 0], [28, 28, 1])
        .toFloat()
        .div(255)
        .reshape([1, 28, 28, 1])
    //   tf.browser.fromPixels(img, 1).toFloat().expandDims(0)
  );
```

**Comment by larswaechter** [comment]
I've also used the `resizeBilinear()` function before, but I noticed a huge quality loss and strange color effects on the images after applying it. See the screenshot below. That's why I used the Python backend for resizing. Here, I don't have those effects.

I have no idea where those color effects come from. You might want to check out what your images look like after applying `resizeBilinear()`. Let me know what you found out :)

![screenshot](https://user-images.githubusercontent.com/11744028/212966269-3f3622a2-bd49-4397-a8cf-c4a740b4a4c8.png)
